### ISSUE TITLE
flight dataset release

### ISSUE THREAD

**Issue by allenc** [ETH-PBL/Matrix_ToF_Drones#1]
hi guys, i'm wondering if ya'll are still planning to release the collected dataset described in https://arxiv.org/abs/2208.12624. cool work btw, i wanted to play around with the software bits myself :)

**Comment by tommasopolonelli** [comment]
Dear allenc, 

        yes we plan to release the dataset when the paper (that you correctly cited) will be officially accepted by the scientific community. Probably this will happen in 2 months.
