### ISSUE TITLE
Final_Assembly_3D.pdf link is a blank PDF

### ISSUE THREAD

**Issue by williamleong** [ETH-PBL/Matrix_ToF_Drones#2]
The final assembly PDF linked from the main page seems to be blank:

```
https://github.com/ETH-PBL/Matrix_ToF_Drones/blob/main/Hardware/MultiBoard_Project/Outputs/Assembly1.pdf
```

**Comment by ETH-PBL** [comment]
Fixed, thanks

**Comment by williamleong** [comment]
In the PCB section (https://github.com/ETH-PBL/Matrix_ToF_Drones?tab=readme-ov-file#pcb), there is a `[Final_Assembly_3D.pdf](https://github.com/ETH-PBL/Matrix_ToF_Drones/blob/main/Hardware/MultiBoard_Project/Outputs/Assembly1.pdf)` link, and in the Material section (https://github.com/ETH-PBL/Matrix_ToF_Drones?tab=readme-ov-file#material) there is the same link `[Final_Assembly_3D.pdf](https://github.com/ETH-PBL/Matrix_ToF_Drones/blob/main/Hardware/MultiBoard_Project/Outputs/Assembly1.pdf` and both now show `404 - page not found`.

I also tried to look at the commit and the file `Hardware/MultiBoard_Project/Assembly_3D.pdf` was changed, but it is also a blank PDF.

**Comment by tommasopolonelli** [comment]
fixed thanks

**Comment by williamleong** [comment]
Is the linked file at `https://github.com/ETH-PBL/Matrix_ToF_Drones/blob/main/Hardware/MultiBoard_Project/Assembly_3D.pdf` is meant to be a blank PDF?

**Comment by tommasopolonelli** [comment]
Is not blank, you have to enable the 3D view in Adobe Reader

**Comment by williamleong** [comment]
Thanks, I have done that and I am able to view it now. Appreciate your clarification.
