### ISSUE TITLE
Easily Use?

### ISSUE THREAD

**Issue by Omikaa** [ETH-PBL/Matrix_ToF_Drones#3]
Hello,
If I get the Sensor Deck and ToF Deck, is it easy to use on the CF following the tutorials?
Is there any need to make some changes on the STM32？I am a little worried about the demand of professional hardware understanding.

**Comment by tommasopolonelli** [comment]
Yes you need to modify the firmware to support the ToF Deck.

**Comment by AZyfen** [comment]
> Hello, If I get the Sensor Deck and ToF Deck, is it easy to use on the CF following the tutorials? Is there any need to make some changes on the STM32？I am a little worried about the demand of professional hardware understanding.

Hello, have you implemented this code? How can I solve the issue of it not flying stably?
